export default {
  login: "/integral/login.do", //登录接口:
  index: "/integral/manager/index.do", //首页接口:
  integralQuery: "/integral/manager/integralQuery.do", //积分排名查询接口:
  ticketQuery: "/integral/manager/ticketQuery.do", //奖券排名查询接口:
  applyList: "/integral/manager/my/applyList.do", //我的_申请列表接口:
  applyDetailList: "/integral/manager/my/applyDetailList.do", //我的_申请详情查询接口:
  applyIntegral: "/integral/manager/my/applyIntegral.do", //我的_申请积分接口:
  integralNameList: "/integral/manager/my/integralNameList.do", //我的_奖项名称和对应ID列表接口:
  integralDetailQuery: "/integral/manager/index/integraDetailQuery.do", //首页_积分明细查询接口__我的_积分明细查询接口:
  list: "/integral/manager/approval/list.do", //审批列表接口:
  detailList: "/integral/manager/approval/detailList.do", //审批列表详情查询接口:
  info: "/integral/manager/approval/info.do", //审批接口:
  staff_list: "/integral/manager/staff/list.do", //员工列表接口:
  staff_detailList: "/integral/manager/staff/detailList.do", //员工详情接口:
  staff_delete: "/integral/manager/staff/del.do", //删除员工接口:
  staff_add: "/integral/manager/staff/add.do", //新增员工接口:
  encourageStaff_list: "/integral/manager/encourageStaff/list.do", //员工奖扣记录接口:
  encourageStaff_add: "/integral/manager/encourageStaff/add.do", //新增员工奖扣接口:
  encourageStaff_delete: "/integral/manager/encourageStaff/del.do", //删除员工奖扣接口:
  store_list: "/integral/manager/store/list.do", //门店列表接口:
  store_detailList: "/integral/manager/store/detailList.do", //门店详情接口:
  store_add: "/integral/manager/store/add.do", //新增门店接口:
  store_delete: "/integral/manager/store/del.do", //删除门店接口:
  rule_list: "/integral/manager/rule/list.do", //积分规则列表查询:
  rule_detailList: "/integral/manager/rule/detailList.do", //积分规则列表详情:
  rule_add: "/integral/manager/rule/add.do", //新增积分规则:
  rule_delete: "/integral/manager/rule/del.do" //删除积分规则:
};
